# Generated by Django 5.0.1 on 2024-02-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendstatus',
            name='status',
            field=models.TextField(choices=[('N', 'None'), ('F', 'Friends'), ('P', 'Pending')]),
        ),
    ]
