# Generated by Django 5.0.1 on 2024-03-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendstatus',
            name='status',
            field=models.TextField(choices=[('P', 'Pending'), ('F', 'Friends'), ('N', 'None')]),
        ),
    ]
