# Generated by Django 5.0.1 on 2024-02-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_friendstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendstatus',
            name='status',
            field=models.TextField(choices=[('P', 'Pending'), ('F', 'Friends'), ('N', 'None')]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
